### ISSUE TITLE
you might have seen this ?

### ISSUE THREAD

**Issue by joeblew99** [nii236/go-react-webpack#1]
https://github.com/scritch007/goa/tree/gopherjs

Using gopherjs with goa allot more.

Your react front end is great. I am playing around with it, and also gopherjs too

**Comment by nii236** [comment]
Thanks for the info! 

Note that `goa` development speed is approaching lightspeed/javascript levels, so you might find that any forks of `goa` will result in an out of date fork in no time at all.
